name: Reactor 5 CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          python3 -m pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true

  build:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t reactor5:latest .

      - name: Run container tests
        run: |
          docker run --rm reactor5:latest python3 -m pytest

      - name: Check container health
        run: |
          docker run -d --name reactor5_test -p 5001:5000 reactor5:latest
          sleep 10
          curl -f http://localhost:5001/ || exit 1
          docker stop reactor5_test
          docker rm reactor5_test

  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install linting tools
        run: |
          pip3 install --upgrade pip
          pip3 install flake8 black isort

      - name: Run linters
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          black . --check
          isort . --check-only --profile black 